version: 2.1

workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true  # Sử dụng máy ảo CircleCI
    steps:
      - run:
          name: Cập nhật danh sách gói
          command: sudo apt update
      - run:
          name: Cài đặt Neofetch
          command: sudo apt install -y neofetch
      - run:
          name: Hiển thị thông tin hệ thống
          command: neofetch
      - run:
          name: Kiểm tra Docker containers đang chạy
          command: docker ps || echo "Docker chưa chạy hoặc không có container nào đang chạy"
      - run:
          name: Kiểm tra Docker daemon
          command: |
            if pgrep dockerd > /dev/null; then
              echo "Docker daemon đang chạy"
            else
              echo "Docker daemon KHÔNG chạy"
            fi
      - run:
          name: Cài đặt Speedtest CLI
          command: sudo apt install -y speedtest-cli
      - run:
          name: Kiểm tra tốc độ mạng
          command: speedtest-cli
