version: 2.1

workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true
    steps:
      - run:
          name: Khởi động container Ubuntu Gnome VNC
          command: |
            sudo docker run --name=ubuntu-gnome -d \
              --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
              --cap-add SYS_BOOT --cap-add SYS_ADMIN \
              --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup \
              -p 5901:5901 -p 6901:6901 \
              darkdragon001/ubuntu-gnome-vnc:2.1

      - run:
          name: Cài đặt Code-Server và Cloudflared
          command: |
            if ! command -v code-server &> /dev/null; then
              curl -fsSL https://code-server.dev/install.sh | sh
            fi
            nohup code-server --bind-addr 0.0.0.0:9999 --auth none > /dev/null 2>&1 &

            if ! command -v cloudflared &> /dev/null; then
              npm install -g cloudflared
            fi
            nohup cloudflared tunnel --url http://localhost:6901 > /dev/null 2>&1 &
