version: 2.1

workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true
    steps:
      - run:
          name: Khởi động container Ubuntu Gnome VNC
          command: |
            sudo docker run --name=ubuntu-gnome -d --rm \
              --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
              --cap-add SYS_BOOT --cap-add SYS_ADMIN \
              --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup \
              -p 5901:5901 -p 6091:6091 \
              darkdragon001/ubuntu-gnome-vnc

            echo "Đợi container Ubuntu-Gnome VNC khởi động..."
            sleep 10  # Đợi container khởi động hoàn toàn

      - run:
          name: Cài đặt và chạy Cloudflare Tunnel
          command: |
            echo "Cài đặt Cloudflared..."
            if ! command -v cloudflared &> /dev/null; then
              npm install -g cloudflared
            fi

            echo "Chạy Cloudflare Tunnel qua cổng 6091..."
            nohup cloudflared tunnel --no-autoupdate --metrics localhost:9090 --url http://localhost:6091 > cloudflared.log 2>&1 &

            echo "Đợi 5 giây để lấy URL Cloudflare Tunnel..."
            sleep 5

            # Lấy URL từ log
            URL=$(grep -o 'https://[a-zA-Z0-9.-]*\.trycloudflare\.com' cloudflared.log | tail -1)
            if [[ -z "$URL" ]]; then
              echo "Không thể lấy URL từ Cloudflared! Kiểm tra log: cat cloudflared.log"
              exit 1
            fi

            echo "Cloudflare Tunnel URL: $URL"
