version: 2.1

workflows:
  build:
    jobs:
      - deploy

jobs:
  deploy:
    machine: true  # Sử dụng máy ảo CircleCI
    steps:
      - run:
          name: Triển khai môi trường và lấy URL public
          command: |
            set -e  # Dừng script nếu có lỗi nghiêm trọng

            echo "--- Kéo và chạy container Docker ---"
            docker pull darkdragon001/ubuntu-gnome-vnc || { echo "Lỗi: Không thể tải container!"; exit 1; }
            sudo docker run --name=ubuntu-gnome -d --rm \
              --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
              --cap-add SYS_BOOT --cap-add SYS_ADMIN \
              --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup \
              -p 5901:5901 -p 6901:6901 \
              darkdragon001/ubuntu-gnome-vnc || { echo "Lỗi: Không thể chạy container!"; exit 1; }

            echo "--- Cài đặt Code-Server ---"
            curl -fsSL https://code-server.dev/install.sh | sh || { echo "Lỗi: Cài đặt Code-Server thất bại!"; exit 1; }
            code-server --bind-addr 0.0.0.0:9999 --auth none &
            sleep 10
            if ! pgrep -f code-server; then echo "Lỗi: Code-Server không khởi động!"; exit 1; fi

            echo "--- Cài đặt Ngrok và lấy URL ---"
            sudo npm install -g ngrok || true
            ngrok authtoken 2uAw45t5PKrzf94kAffkqq4Pbo4_2Hd1XWPUirfVS2J9fmaSo || { echo "Lỗi: Ngrok auth token không hợp lệ!"; exit 1; }
            ngrok http --region=us 9999 | tee /tmp/ngrok.log &
            sleep 10
            NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url' || echo "Lỗi: Không thể lấy URL Ngrok!")
            echo "Ngrok URL: $NGROK_URL"

            echo "--- Cài đặt Cloudflared và lấy URL ---"
            sudo npm install -g cloudflared || true
            sudo sysctl -w net.core.rmem_max=2500000
            sudo sysctl -w net.core.rmem_default=2500000
            cloudflared tunnel --ha-connections=1 --url http://localhost:6901 | tee /tmp/cloudflared.log &
            sleep 15
            CLOUDFLARED_URL=$(grep -oP 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' /tmp/cloudflared.log | head -1 || echo "Lỗi: Không thể lấy URL Cloudflared!")
            echo "Cloudflared URL: $CLOUDFLARED_URL"

            echo "--- Giữ job luôn chạy ---"
            tail -f /dev/null
