version: 2.1

workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true
    steps:
      - run:
          name: Kéo image Ubuntu Gnome VNC
          command: |
            sudo docker pull darkdragon001/ubuntu-gnome-vnc

      - run:
          name: Khởi động container Ubuntu Gnome VNC
          command: |
            sudo docker run --name=ubuntu-gnome -d --rm \
              --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
              --cap-add SYS_BOOT --cap-add SYS_ADMIN \
              --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup \
              -p 5901:5901 -p 6091:6091 \
              darkdragon001/ubuntu-gnome-vnc

            echo "Đợi container Ubuntu-Gnome VNC khởi động..."
            sleep 10  # Giảm thời gian chờ nhưng vẫn đảm bảo đủ

            echo "Kiểm tra container có chạy đúng không..."
            sudo docker ps

            echo "Kiểm tra cổng 6091 có mở không..."
            sudo ss -tulnp | grep 6091 || echo "LỖI: Cổng 6091 chưa mở!"

      - run:
          name: Cài đặt và chạy Cloudflare Tunnel (Luôn chạy)
          command: |
            echo "Cài đặt Cloudflared..."
            if ! command -v cloudflared &> /dev/null; then
              npm install -g cloudflared
            fi

            echo "Chạy Cloudflare Tunnel qua cổng 6091..."
            nohup cloudflared tunnel --no-autoupdate --url http://localhost:6091 > cloudflared.log 2>&1 &

            sleep 5  # Đợi một chút để lấy URL
            echo "Cloudflare Tunnel đang chạy, kiểm tra URL..."

            tail -n 10 cloudflared.log | grep "trycloudflare.com" || echo "LỖI: Không lấy được URL Cloudflare!"

            # Giữ tiến trình chạy mãi mãi
            tail -f /dev/null
