version: 2.1

workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true  # Sử dụng máy ảo CircleCI
    steps:
      - run:
          name: Thiết lập môi trường root và chạy Docker Ubuntu-Gnome-VNC với Ngrok
          command: |
            sudo bash -c "
            echo 'Đã chuyển sang quyền root';
            # Cài đặt nvm (Node Version Manager)
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
            export NVM_DIR=\"$HOME/.nvm\"
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"
            # Cài đặt Node.js phiên bản mới nhất
            nvm install --lts
            # Kiểm tra phiên bản Node.js và npm
            node -v
            npm -v
            docker run --name=ubuntu-gnome -d --rm \
              --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
              -p 5901:5901 -p 6901:6901 \
              darkdragon001/ubuntu-gnome-vnc;
            sleep 10;
            echo 'Cài đặt và khởi chạy Ngrok';
            npm install -g ngrok;
            ngrok config add-authtoken 2uAsCE7GYETsULqdZsQEWDk6hjg_3jM9x6q8RzdmSmJher9io;
            ngrok http 5901 & sleep 15;
            echo 'Lấy URL public từ Ngrok';
            curl -s http://127.0.0.1:4040/api/tunnels | grep -o '\"public_url\":\"[^\"]*' | cut -d '\"' -f4
            "
      - run:
          name: Giữ job luôn chạy bằng tail -f
          command: |
            # Tạo một tệp log trống
            touch /tmp/keep-alive.log
            # Sử dụng tail -f để theo dõi tệp log (sẽ không bao giờ kết thúc)
            tail -f /tmp/keep-alive.log
