workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true  # Sử dụng máy ảo CircleCI
    steps:
      - run:
          name: Cài đặt Code-Server và thiết lập Ngrok
          command: |
            curl -fsSL https://code-server.dev/install.sh | sh && \
            code-server --bind-addr 0.0.0.0:9999 --auth none & \
            sleep 5 && \
            npm install -g ngrok && \
            ngrok config add-authtoken 2uARyZ1iAmLrdb1iXHkh5RQv7QG_3y6HxJYXJXdCDtTQvgu3c && \
            ngrok http 9999 | tee ngrok.log & \
            sleep 10 && \
            curl -s http://127.0.0.1:4040/api/tunnels | grep -o '"public_url":"[^"]*' | cut -d '"' -f4
