version: 2.1

workflows:
  build:
    jobs:
      - system_check

jobs:
  system_check:
    machine: true  # Sử dụng máy ảo CircleCI
    steps:
      - run:
          name: Thiết lập môi trường root và chạy Docker Ubuntu-Gnome-VNC với Ngrok
          command: |
            sudo -i bash -c "
            echo 'Đã chuyển sang quyền root';
            docker run --name=ubuntu-gnome -d --rm \
              --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
              --cap-add SYS_BOOT --cap-add SYS_ADMIN \
              --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup \
              -p 5901:5901 -p 6901:6901 \
              darkdragon001/ubuntu-gnome-vnc;
            sleep 5;
            echo 'Cài đặt NVM, Node.js và Ngrok';
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash;
            export NVM_DIR="$HOME/.nvm";
            [ -s "$NVM_DIR/nvm.sh" ] && \ . "$NVM_DIR/nvm.sh";
            [ -s "$NVM_DIR/bash_completion" ] && \ . "$NVM_DIR/bash_completion";
            nvm install 22.9.0;
            nvm use 22.9.0;
            npm install -g npm;
            npm install -g ngrok;
            ngrok config add-authtoken 2uARyZ1iAmLrdb1iXHkh5RQv7QG_3y6HxJYXJXdCDtTQvgu3c;
            ngrok http 6091 & sleep 10;
            echo 'Lấy URL public từ Ngrok';
            curl -s http://127.0.0.1:4040/api/tunnels | grep -o '\"public_url\":\"[^\"]*' | cut -d '\"' -f4
            "
